experiment_name: vit_b16_baseline
seed: 42
num_classes: 40
device: cuda
gpu_id: 0
output_dir: outputs

data:
  train_csv: /root/trunglm8/upar_challenge/raw_data/train.csv
  val_csv: /root/trunglm8/upar_challenge/raw_data/val.csv
  test_csv: /root/trunglm8/upar_challenge/raw_data/test.csv
  img_dirs:
    - /root/trunglm8/upar_challenge/raw_data/data/Market1501/bounding_box_train
    - /root/trunglm8/upar_challenge/raw_data/data/PA100k/release_data/release_data
    - /root/trunglm8/upar_challenge/raw_data/data/PETA/images
  image_size: [224, 224]
  batch_size: 32
  num_workers: 4
  skiprows: 1

model:
  name: vit_b16
  pretrained: true
  dropout: 0.1

loss:
  name: bce
  use_auto_class_weight: true

train:
  epochs: 25
  lr: 0.0001
  weight_decay: 0.001
  step_size: 40
  gamma: 0.1
  scheduler : cosine