from .resnet_attr import ResNetAttrModel
from .efficientnet_attr import EfficientNetAttrModel
from .vit_attr import ViTAttrModel
from .swin_attr import SwinAttrModel
from .pcb_attr import PCBAttrModel
from .pcb_real import PCBRealAttrModel
from .hybrid_effb0_transformer import HybridEfficientNetTransformer
from .dual_branch_effb0_swin import DualBranchEfficientNetSwin
from .effb0_part_attr import EfficientNetB0PartAttrModel
from .resnet_update import ResNetUpdateModel
from .efficientnet_update import EfficientNetUpdateModel